export interface Stock {
  ticker: string;
  name: string;
}

export const STOCKS: Stock[] = [
  { ticker: "AAPL", name: "Apple Inc." },
  { ticker: "MSFT", name: "Microsoft Corporation" },
  { ticker: "NVDA", name: "NVIDIA Corporation" },
  { ticker: "AMZN", name: "Amazon.com Inc." },
  { ticker: "GOOGL", name: "Alphabet Inc. (Class A)" },
  { ticker: "GOOG", name: "Alphabet Inc. (Class C)" },
  { ticker: "META", name: "Meta Platforms Inc." },
  { ticker: "TSLA", name: "Tesla Inc." },
  { ticker: "BRK.B", name: "Berkshire Hathaway Inc." },
  { ticker: "JPM", name: "JPMorgan Chase & Co." },
  { ticker: "V", name: "Visa Inc." },
  { ticker: "UNH", name: "UnitedHealth Group Inc." },
  { ticker: "XOM", name: "Exxon Mobil Corporation" },
  { ticker: "MA", name: "Mastercard Inc." },
  { ticker: "LLY", name: "Eli Lilly and Company" },
  { ticker: "JNJ", name: "Johnson & Johnson" },
  { ticker: "HD", name: "The Home Depot Inc." },
  { ticker: "AVGO", name: "Broadcom Inc." },
  { ticker: "PG", name: "Procter & Gamble Co." },
  { ticker: "COST", name: "Costco Wholesale Corporation" },
  { ticker: "MRK", name: "Merck & Co. Inc." },
  { ticker: "ABBV", name: "AbbVie Inc." },
  { ticker: "CVX", name: "Chevron Corporation" },
  { ticker: "KO", name: "The Coca-Cola Company" },
  { ticker: "PEP", name: "PepsiCo Inc." },
  { ticker: "WMT", name: "Walmart Inc." },
  { ticker: "AMD", name: "Advanced Micro Devices Inc." },
  { ticker: "NFLX", name: "Netflix Inc." },
  { ticker: "BAC", name: "Bank of America Corporation" },
  { ticker: "DIS", name: "The Walt Disney Company" },
  { ticker: "ADBE", name: "Adobe Inc." },
  { ticker: "CRM", name: "Salesforce Inc." },
  { ticker: "ORCL", name: "Oracle Corporation" },
  { ticker: "INTC", name: "Intel Corporation" },
  { ticker: "QCOM", name: "Qualcomm Inc." },
  { ticker: "IBM", name: "International Business Machines" },
  { ticker: "TXN", name: "Texas Instruments Inc." },
  { ticker: "GS", name: "The Goldman Sachs Group Inc." },
  { ticker: "MS", name: "Morgan Stanley" },
  { ticker: "WFC", name: "Wells Fargo & Company" },
  { ticker: "C", name: "Citigroup Inc." },
  { ticker: "UBER", name: "Uber Technologies Inc." },
  { ticker: "LYFT", name: "Lyft Inc." },
  { ticker: "ABNB", name: "Airbnb Inc." },
  { ticker: "SHOP", name: "Shopify Inc." },
  { ticker: "SQ", name: "Block Inc." },
  { ticker: "PYPL", name: "PayPal Holdings Inc." },
  { ticker: "COIN", name: "Coinbase Global Inc." },
  { ticker: "HOOD", name: "Robinhood Markets Inc." },
  { ticker: "PLTR", name: "Palantir Technologies Inc." },
  { ticker: "SNOW", name: "Snowflake Inc." },
  { ticker: "NET", name: "Cloudflare Inc." },
  { ticker: "CRWD", name: "CrowdStrike Holdings Inc." },
  { ticker: "PANW", name: "Palo Alto Networks Inc." },
  { ticker: "ZS", name: "Zscaler Inc." },
  { ticker: "DDOG", name: "Datadog Inc." },
  { ticker: "MDB", name: "MongoDB Inc." },
  { ticker: "TWLO", name: "Twilio Inc." },
  { ticker: "RBLX", name: "Roblox Corporation" },
  { ticker: "SPOT", name: "Spotify Technology S.A." },
  { ticker: "SNAP", name: "Snap Inc." },
  { ticker: "PINS", name: "Pinterest Inc." },
  { ticker: "RIVN", name: "Rivian Automotive Inc." },
  { ticker: "LCID", name: "Lucid Group Inc." },
  { ticker: "NIO", name: "NIO Inc." },
  { ticker: "BABA", name: "Alibaba Group Holding Ltd." },
  { ticker: "JD", name: "JD.com Inc." },
  { ticker: "PDD", name: "PDD Holdings Inc." },
  { ticker: "TSM", name: "Taiwan Semiconductor Mfg. Co." },
  { ticker: "ASML", name: "ASML Holding N.V." },
  { ticker: "SAP", name: "SAP SE" },
  { ticker: "TM", name: "Toyota Motor Corporation" },
  { ticker: "SONY", name: "Sony Group Corporation" },
  { ticker: "ARM", name: "Arm Holdings plc" },
  { ticker: "SMCI", name: "Super Micro Computer Inc." },
  { ticker: "MU", name: "Micron Technology Inc." },
  { ticker: "LRCX", name: "Lam Research Corporation" },
  { ticker: "AMAT", name: "Applied Materials Inc." },
  { ticker: "KLAC", name: "KLA Corporation" },
  { ticker: "ON", name: "ON Semiconductor Corporation" },
  { ticker: "HPQ", name: "HP Inc." },
  { ticker: "DELL", name: "Dell Technologies Inc." },
  { ticker: "HPE", name: "Hewlett Packard Enterprise Co." },
  { ticker: "ACN", name: "Accenture plc" },
  { ticker: "NOW", name: "ServiceNow Inc." },
  { ticker: "INTU", name: "Intuit Inc." },
  { ticker: "ISRG", name: "Intuitive Surgical Inc." },
  { ticker: "VRTX", name: "Vertex Pharmaceuticals Inc." },
  { ticker: "REGN", name: "Regeneron Pharmaceuticals Inc." },
  { ticker: "GILD", name: "Gilead Sciences Inc." },
  { ticker: "AMGN", name: "Amgen Inc." },
  { ticker: "BMY", name: "Bristol-Myers Squibb Company" },
  { ticker: "PFE", name: "Pfizer Inc." },
  { ticker: "MRNA", name: "Moderna Inc." },
  { ticker: "ZM", name: "Zoom Video Communications Inc." },
  { ticker: "DOCU", name: "DocuSign Inc." },
  { ticker: "OKTA", name: "Okta Inc." },
  { ticker: "HUBS", name: "HubSpot Inc." },
  { ticker: "TTD", name: "The Trade Desk Inc." },
  { ticker: "APP", name: "AppLovin Corporation" },
  { ticker: "CELH", name: "Celsius Holdings Inc." },
  { ticker: "MSTR", name: "MicroStrategy Inc." },
  { ticker: "GME", name: "GameStop Corp." },
  { ticker: "AMC", name: "AMC Entertainment Holdings" },
];

export function searchStocks(query: string): Stock[] {
  const q = query.trim().toUpperCase();
  if (!q) return [];
  return STOCKS.filter(
    (s) =>
      s.ticker.startsWith(q) ||
      s.name.toUpperCase().includes(q)
  ).slice(0, 8);
}
